# Competition configuration options
options:
  insert_models_over_bins: true     # Whether or not to insert the models that are specified in models_over_bins
  spawn_extra_models: true          # Whether or not to spawn the models that are specified in models_to_spawn
  fill_demo_shipment: true          # If true, the first shipping box will have products from the first order spawned
                                    # directly in it once the competition starts (for testing purposes)
  start_box_at_belt_center: true    # If true, the first shipping box will start in the middle of the belt
  gazebo_state_logging: true        # Whether or not to generate a gazebo state log
  belt_population_cycles: 5         # How many of each shipping box to spawn on the belt beyond the first
  model_type_aliases:               # Aliases for model types which can be used in the configuration file
    order_part1: piston_rod_part    # Wherever 'order_part1' is used in the configuration file, use 'piston_rod_part'
    order_part2: gear_part
    order_part3: pulley_part

time_limit: 500                      # Maximum time allowed for the trial once started, in seconds
random_seed: 1                       # Seed for the pseudo random number generator (used to randomize model names)

# Orders to announce during the trial
orders:
  order_0:
    announcement_condition: time     # Announce the order base on elapsed time
    announcement_condition_value: 0  # Time in seconds to wait before announcing the order
    shipment_count: 1                # How many of the same shipment are in the order
    products:                        # List of products required to be in the kit
      part_0:
        type: order_part1            # Type of model required
        pose:
          xyz: [0.1, -0.15, 0]       # Position required in the shipping box frame
          rpy: [0, 0, 'pi/2']        # Orientation required in the shipping box frame
      part_1:
        type: order_part1
        pose:
          xyz: [-0.1, -0.15, 0]
          rpy: [0, 0, 'pi/2']
      part_2:
        type: order_part2
        pose:
          xyz: [0.1, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]
  order_1:
    announcement_condition: wanted_products # Announce the order when the boxes contain products from this order
    announcement_condition_value: 2
    shipment_count: 1
    products:
      part_0:
        type: order_part3
        pose:
          xyz: [0.12, -0.2, 0]
          rpy: ['pi', 0, 0]
      part_1:
        type: order_part3
        pose:
          xyz: [-0.12, -0.2, 0]
          rpy: [0, 'pi', 0]
      part_2:
        type: order_part1
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_4:
        type: order_part2
        pose:
          rpy: [0, 'pi', 0]

# Individual products that will be reported as faulty
faulty_products:
  - piston_rod_part_57                # The piston rod part in the bins with randomized ID of 57
  - piston_rod_part_45

# Models to be inserted in the bins
models_over_bins:
  bin3:                              # Name of the bin (bin1-bin5, as named in the environment simulation)
    models:                          # List of models to insert
      gear_part:                     # Type of model to insert
        xyz_start: [0, 0, 0]         # Origin of the first model to insert
        xyz_end: [0.3, 0.37, 0]      # Origin of the last model to insert
        rpy: [0, 0, 'pi/4']          # Orientation of all models to insert
        num_models_x: 3              # How many models to insert along the x dimension
        num_models_y: 5              # How many models to insert along the y dimension
  bin4:
    models:
      gasket_part:
        xyz_start: [0.0, 0.05, 0.0]
        xyz_end: [0.2, 0.37, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3
  bin5:
    models:
      piston_rod_part:
        xyz_start: [0.0, 0.0, 0.0]
        xyz_end: [0.25, 0.35, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3

# Models to be spawned in particular reference frames
models_to_spawn:
  bin2::link:                        # Name of the reference frame
    models:                          # List of models to spawn
      piston_rod_part_1:             # An arbitrary unique name of the model (will be randomized)
        type: piston_rod_part        # Type of model (must be installed locally)
        pose:
          xyz: [0.1, 0.1, 0.25]      # Co-ordinates of the model origin in the specified reference frame
          rpy: [0, 0, '-pi/2']       # Roll, pitch, yaw of the model in the specified reference frame
drops:
  drop_regions:
    agv1_impeding:
      min:
        xyz: [0.0, 2.7, 0.6]
      max:
        xyz: [0.6, 3.5, 1.5]
      destination:                   # Where to drop the part to (world co-ordinates)
        xyz: [0.4, 3.1, 0.8]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gear_part
    agv2_impeding:
      min:
        xyz: [0.0, -2.7, 0.6]
      max:
        xyz: [0.6, -3.5, 1.5]
      destination:
        xyz: [0.4, -3.1, 0.8]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gear_part
    bin3_reachable:
      min:
        xyz: [-0.85, 0.7, 0.7]
      max:
        xyz: [-0.65, 1.60, 1.3]
      destination:
        xyz: [-0.65, 1.15, 0.76]
        rpy: [0, 0, 0.5]
      product_type_to_drop: gear_part
